language: nix
sudo: false

script: nix-shell --run 'sbt clean coverage +test'

after_success:
  - nix-shell --run 'coverageReport coverageAggregate'
  - nix-shell --run 'sbt coveralls'

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2

branches:
  only:
    - master
